tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed-variant": "#4d1c85",
                "on-secondary-container": "#842141",
                "error-container": "#f95630",
                "primary-fixed": "#ff7576",
                "primary-container": "#ff7576",
                "secondary-fixed": "#ffc2cd",
                "on-surface-variant": "#814c58",
                "on-tertiary-fixed": "#25004b",
                "on-error-container": "#520c00",
                "on-primary": "#ffefee",
                "tertiary-fixed-dim": "#bd8df9",
                "error-dim": "#b92902",
                "surface": "#fff4f4",
                "on-primary-fixed-variant": "#60000f",
                "inverse-on-surface": "#ca8c98",
                "secondary-dim": "#8e2a49",
                "tertiary-fixed": "#c99dff",
                "surface-container-highest": "#ffd1d9",
                "surface-container": "#ffe1e5",
                "on-primary-container": "#4e000a",
                "inverse-primary": "#f9595f",
                "surface-tint": "#af2330",
                "on-tertiary-container": "#440e7c",
                "surface-variant": "#ffd1d9",
                "outline-variant": "#dc9ca8",
                "on-primary-fixed": "#000000",
                "tertiary-container": "#c99dff",
                "outline": "#a06773",
                "primary-fixed-dim": "#fc5c61",
                "surface-dim": "#ffc6d0",
                "secondary": "#9e3655",
                "on-secondary-fixed-variant": "#902b4a",
                "tertiary-dim": "#65379d",
                "primary-dim": "#9e1425",
                "on-secondary": "#ffeff0",
                "on-secondary-fixed": "#6a0a2f",
                "on-error": "#ffefec",
                "on-background": "#4c212c",
                "inverse-surface": "#24020c",
                "surface-container-high": "#ffd9df",
                "surface-container-low": "#ffecee",
                "surface-container-lowest": "#ffffff",
                "surface-bright": "#fff4f4",
                "on-tertiary": "#faefff",
                primary: "#af2330",
                "secondary-fixed-dim": "#ffadbe",
                "secondary-container": "#ffc2cd",
                error: "#b02500",
                "on-surface": "#4c212c",
                background: "#fff4f4",
                tertiary: "#7144aa"
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                xl: "80px",
                base: "8px",
                "max-width": "1200px",
                md: "24px",
                lg: "48px",
                "margin-desktop": "auto",
                sm: "12px",
                "margin-mobile": "20px",
                gutter: "16px",
                xs: "4px"
            },
            fontFamily: {
                "label-caps": ["Plus Jakarta Sans"],
                "body-lg": ["Inter"],
                "headline-lg": ["Plus Jakarta Sans"],
                "character-display": ["Noto Serif SC"],
                "headline-md": ["Plus Jakarta Sans"],
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Plus Jakarta Sans"]
            },
            fontSize: {
                "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
                "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
                "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "character-display": ["64px", { lineHeight: "80px", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "headline-lg-mobile": ["32px", { lineHeight: "38px", fontWeight: "700" }]
            }
        }
    }
};